apiVersion: v1
kind: Namespace
metadata:
  name: nsitzel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-disco-itzel
  namespace: nsitzel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: nsitzel
type: Opaque
data:
  password: aXR6ZWw=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy-itzel
  namespace: nsitzel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itzelmysql
  template:
    metadata:
      labels:
        app: itzelmysql
    spec:
      containers:
        - name: itzelmysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
          ports:
            - containerPort: 3306
              name: itzelmysql
          volumeMounts:
            - name: itzmysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: itzmysql-data
          persistentVolumeClaim:
            claimName: mysql-disco-itzel
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-itzel
  namespace: nsitzel
spec:
  selector:
    app: itzelmysql
  type: ClusterIP
  ports:
    - name: itzelmysql
      port: 3306
      targetPort: 3306
